Update README.md
PDOK/lighttpd-docker pull request #13
Opened 2022-08-17 14:41 UTC by arbakker

# Omschrijving

Update README.md.

2022-08-18 08:11 UTC, roelarents requested changes

2022-08-18 08:11 UTC, roelarents commented on README.md
> +### Enable Dockerfile inting pre-commit hook
```suggestion
### Enable Dockerfile linting pre-commit hook
```

2022-08-18 08:11 UTC, roelarents commented on README.md
> +Succesfull Dockerfile linting is a requirement for merging pull requests to master, which is enforced with the [Dockerfile Lint Github action](https://github.com/PDOK/lighttpd-docker/blob/master/.git
```suggestion
Successful Dockerfile linting is a requirement for merging pull requests into
master, which is enforced with the [Dockerfile Lint Github action](
https://github.com/PDOK/lighttpd-docker/blob/master/.github/workflows/dockerfile-lint.yaml).
```

2022-10-18 13:56 UTC, WouterVisscher approved these changes

2022-10-18 15:33 UTC, roelarents approved these changes
huh? ok

2022-10-18 15:34 UTC, merged